# Generated by Django 4.1.7 on 2023-03-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_metal', models.CharField(choices=[('Au', 'Gold'), ('Ag', 'Silver'), ('Pt', 'Platinum')], max_length=10)),
                ('value_USD', models.IntegerField()),
            ],
        ),
    ]
